version: 0.0
os: linux
files:
  - source: conversationService/
    destination: /home/ec2-user/venos/conversationService/
  - source: docker/
    destination: /home/ec2-user/venos/docker/
  - source: orderService/
    destination: /home/ec2-user/venos/orderService/
  - source: package-lock.json
    destination: /home/ec2-user/venos/package-lock.json
  - source: README.md
    destination: /home/ec2-user/venos/README.md
  - source: deploy.sh
    destination: /home/ec2-user/venos/deploy.sh  
hooks:
  BeforeInstall:
    - location: docker/scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: docker/scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: docker/scripts/application_start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: docker/scripts/validation_start.sh
      timeout: 300
      runas: root