version: 0.0
os: linux
files:
  - source: conversationService
    destination: /home/ec2-user/venos/conversationService
  - source: docker
    destination: /home/ec2-user/venos/docker
  - source: orderService
    destination: /home/ec2-user/venos/orderService
  - source: checkout-page
    destination: /home/ec2-user/venos/checkout-page
  - source: README.md
    destination: /home/ec2-user/venos
  - source: deploy.sh
    destination: /home/ec2-user/venos  
  - source: docker-compose-production.yml
    destination: /home/ec2-user/venos
  - source: docker-compose-staging.yml
    destination: /home/ec2-user/venos
hooks:
  BeforeInstall:
    - location: docker/scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: docker/scripts/after_install.sh
      timeout: 900
      runas: root
  ApplicationStart:
    - location: docker/scripts/application_start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: docker/scripts/validation_start.sh
      timeout: 300
      runas: root