
# container image includes Node.JS 8 as a S2I base image for Node.JS 8 applications
FROM centos:centos7

# installing the NodeSource Node.js 8.x repo...
RUN curl -sL https://rpm.nodesource.com/setup_8.x | bash -

# install nodejs
RUN yum install nodejs -y


 

